### ISSUE TITLE
Buscar plantilla página principal

### ISSUE THREAD

**Issue by pedroprieto** [iesmarenostrum/marenostrumtest#1]
Como referencia inicial de concepto podemos tomar la de http://berlanga.edu.gva.es/web/index.php/es/  

Debe ser gráfica, responsive, que entre por los ojos. 

A la hora de elegir hay que tener en cuenta que en ella vamos a poner Información gráfica y general del centro, oferta formativa, funcionamiento general, programas, prácticas, erasmus, pero todo desde el punto de vista de "vender" el centro sin concretar mucho salvo en la oferta formativa.

Sitios interesantes para mirar:

Plantillas deJekyll:
   http://jekyllthemes.org/
   http://themes.jekyllrc.org/

Plantillas HTML/CSS de pago:
   https://themeforest.net/category/site-templates
   https://www.templatemonster.com/es/plantillas-web-tipo/

De vez en cuando alguna clasificación de estas ayuda:
     https://dcrazed.com/free-responsive-html5-css3-templates/
     https://dcrazed.com/premium-html5-css3-website-templates/

**Comment by pedroprieto** [comment]
Dos páginas:
www.upv.es
www.ua.es

**Comment by administradoriesmn** [comment]
Pongo aquí lo de David, es la issue correcta:

Hola,

a ver que os parecen estas:

Free:

https://mobirise.com/bootstrap-template/one-page.html

https://www.templatemonster.com/demo/53136.html

https://www.templatemonster.com/demo/62028.html

Pago:

Esta es de pago con muchas opciones y distintos tipos de páginas.
http://massivedynamic.co/#

Esta es un ejemplo de la anterior con una especie de línea de noticias.
http://demo.massivedynamic.co/minimal-agency/

**Comment by administradoriesmn** [comment]
La de massive dynamic es para wordpress, pero veo que tienen un buen subconjunto para HTML5 por 17$:

https://themeforest.net/item/massive-responsive-multipurpose-html5-template/12503639

Suena bien para la poca pasta que vale, desde luego

**Comment by administradoriesmn** [comment]
La de https://mobirise.com/bootstrap-template/video-background.html vendría bien mirando cómo queda el vídeo de marisol, en todo, en parte o fragmentos, o haciendo un time-lapse del centro, alumnos o algo.

**Comment by administradoriesmn** [comment]
En la línea de la de david de massive, con una buena pantalla inicial vistosa con fotos y vídeos y con grandes entornos para luego aprovechar en distintos sitios de las webs de perfiles, me han gustado estas dos:

https://themeforest.net/item/haswell-multipurpose-one-multi-page-template/12087194
http://preview.themeforest.net/item/canvas-the-multipurpose-html5-template/full_screen_preview/9228123

**Comment by pedroprieto** [comment]
Massive is the winner!!
