### ISSUE TITLE
Buscar plantilla para webs alumnado presencial y semi

### ISSUE THREAD

**Issue by administradoriesmn** [iesmarenostrum/marenostrumtest#2]
A la hora de elegir hay que tener en cuenta que en ella vamos a poner:

-Información de normativa e interés
-Procesos en gráfico (no calendario, en principio tipo gestor de proyectos)
-Eventos de centro
-Programas y proyectos de su interés (entre ellos FCT y Erasmus y enlace a procesos relacionados)
-Enlaces a webs del centro y relacionadas

Como características generales de concepto:

-No hace falta que sea tan visual como la de inicio, se trata de dar información a alumnos
-Puede tener por tanto menús, barras, secciones, etc
-La parte de eventos normalmente implica galerías de fotos y vídeos.
-En semi es importante,  y también aplicable quizás a presencial, que al menos durante los dos primeros meses haya una información de orientación fácil de encontrar y representativa para que los alumnos den el mínimo porsaco posible. Si durante la búsqueda se ve algún concepto relevante sobre ello, anotadlo.
-Debe haber un botón claro y localizado para cambiar de perfil a profesor, empresa, etc. Si durante la búsqueda se ve algún concepto relevante sobre ello, anotadlo. 

En el caso de semi, y también se podría hacer en presencial, es muy importante tener 

Sitios interesantes para mirar:

Plantillas deJekyll:
http://jekyllthemes.org/
http://themes.jekyllrc.org/

Plantillas HTML/CSS de pago:
https://themeforest.net/category/site-templates
https://www.templatemonster.com/es/plantillas-web-tipo/

De vez en cuando alguna clasificación de estas ayuda:
https://dcrazed.com/free-responsive-html5-css3-templates/
https://dcrazed.com/premium-html5-css3-website-templates/

**Comment by pedroprieto** [comment]
## Propuestas de Pedro
- http://webjeda.com/cards/
- http://webjeda.com/karna/
- http://phlow.github.io/feeling-responsive/

**Comment by gonzalezdelarco** [comment]
Hola,

a ver que os parecen estas:

Free:

https://mobirise.com/bootstrap-template/one-page.html

https://www.templatemonster.com/demo/53136.html

https://www.templatemonster.com/demo/62028.html

Pago:

Esta es de pago con muchas opciones y distintos tipos de páginas.
http://massivedynamic.co/#

Esta es un ejemplo de la anterior con una especie de línea de noticias.
http://demo.massivedynamic.co/minimal-agency/

**Comment by administradoriesmn** [comment]
Pedro, las tuyas bien, dependiendo de la información que tengamos que representar si cabe o tiene que estar más "apretada". Habría que mirar alguna subplantilla para galería de eventos y cosas así, si no vienen en la plantilla.  La más completa la de feeling responsive, pero me sigue oliendo algo casera, igual son cosas mías. Mirando la de david de massive en html5 igual nos vale para todo, luego tiene 1000 subcomponentes.

**Comment by administradoriesmn** [comment]
Tras la página de entrada que ha buscado David, y tras ver muchas templates, se me ocurren dos filosofías generales para poder aglutinar todo lo que queremos meter de información de manera lo más visual y menos casera posible:

https://themeforest.net/item/city-listing-directory-template/19468136
Para todo el sitio web, en vez de ciudades perfiles, es decir, distribuimos entre perfiles, poniendo cosas en los botones de abajo de la búsqueda (inicial y luego tras darle al +) que bien simplemente bajen en scroll o vayan a páginas nuevas.  Tiene mucha variedad aparte de páginas y subpaginas. Sería comenzar con el fondo que deje la página de david en oscuro y a partir de ahí forzar elegir un perfil sin permitir hacer más que ver generalidades

http://keenthemes.com/preview/metronic/
http://preview.themeforest.net/item/service-providers-business-directory-template/full_screen_preview/19652960
http://demo.interface.club/?theme=limitless
Diseño tipo dashboard para cada perfil. Como tenemos mucha información que mostrar, una buena idea puede ser seguir una filosofía tipo "dashboard" de administración, con secciones a la izquierda y arriba y uno de estos temas con un montón de contenedores y plugins, donde meteríamos entre ellos el de eventos que ha visto pedro.

**Comment by administradoriesmn** [comment]
Como temas generales para estas páginas y cualquiera de los otros perfiles, me gustan estos temas:

https://themeforest.net/item/progressive-multipurpose-responsive-template/7197521
De esta me gusta el menú y los componentes, tiene un aire cálido y moderno

https://demo.nkdev.info/#khaki_html
De esta me gusta los componentes, galerías, páginas sueltas, etc

**Comment by pedroprieto** [comment]
Massive también para ésta.
