### ISSUE TITLE
Buscar visualizador de procesos

### ISSUE THREAD

**Issue by administradoriesmn** [iesmarenostrum/marenostrumtest#3]
Necesitamos un visualizador de procesos que implique una línea de tiempo, donde salga todo aquello que le puede preocupar o necesitar un alumno y que tenga fechas y plazos: proyecto, fct, convalidaciones, exámenes, preinscripciones, etc, etc.

La idea inicial es que no se puede poner con un calendario al uso porque no se muestra todo el curso -problema menor- y los procesos no tienen fecha fija (problema mayor)

Una vez que vemos un proceso de nuestro interés, podemos pinchar en él y se nos desplegará la información y documentos relacionados en pestañas, si los hubiera, y sino un campo para meter el email y establecer  un aviso antes de que suceda, durante, y justo antes de acabar el plazo.

La idea inicial, muy vaga, era coger/programar algo al estilo de un gestor de proyectos tipo omniplan pero el tema está muy indefinido:

![original](https://cloud.githubusercontent.com/assets/25039473/24748985/c383cf88-1ac1-11e7-94e7-03f50ddd15d0.jpg)

**Comment by pedroprieto** [comment]
http://visjs.org/timeline_examples.html
Muy potente. JavaScript. Utiliza JSON por detrás. Pulsad en algún enlace y veréis cómo funciona.
La librería hace más cosas: http://visjs.org/

**Comment by administradoriesmn** [comment]
Excelente, no lo conocía y es justo lo que necesitamos

Creo que marcando solo los meses como eje x estará genial, es muy potente

**Comment by pedroprieto** [comment]
Ok pues. Lo dejamos con ése.
